# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class EchallanItem(scrapy.Item):
    vehicle_number = scrapy.Field()
    offences = scrapy.Field()
    custom_offence = scrapy.Field()
    pdf_url = scrapy.Field()
    under_investigate = scrapy.Field()
    receipt_url = scrapy.Field()
    challan_no = scrapy.Field()
    date_time = scrapy.Field()
    lat_long = scrapy.Field()
    officer_id = scrapy.Field()
    designation = scrapy.Field()
    accused_name = scrapy.Field()
    accused_father_name = scrapy.Field()
    address = scrapy.Field()
    owner_name = scrapy.Field()
    chasis_no = scrapy.Field()
    vehicle_class = scrapy.Field()
    challan_status = scrapy.Field()
    payment_date = scrapy.Field()
    doc_no = scrapy.Field()
    payment_source = scrapy.Field()
    mobile_no = scrapy.Field()
    sent_to_court_on = scrapy.Field()
    court_name = scrapy.Field()
    court_address = scrapy.Field()
    traffic_police = scrapy.Field()
    challan_source = scrapy.Field()
    amount = scrapy.Field()
    transaction_id = scrapy.Field()
    vcourt_eligible = scrapy.Field()
    vcourt_transferred_to_court = scrapy.Field()
    vcourt_contested = scrapy.Field()
    court_status = scrapy.Field()
    vehicle_impound = scrapy.Field()
    state_code = scrapy.Field()
    valid_contact_no = scrapy.Field()
    office_name = scrapy.Field()
    area_name = scrapy.Field()
    office_text = scrapy.Field()
    vcourt_eligible_btn = scrapy.Field()
    paymentEligible = scrapy.Field()
    encriptParams = scrapy.Field()
    status_txt = scrapy.Field()
    is_otp_popup_enable = scrapy.Field()
